const styles = {
  card: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    p: { xs: 2, md: 3 },
    borderRadius: 3,
    alignItems: 'flex-start',
  },
  titleBox: {
    width: '100%',
    textAlign: 'center',
    mb: { xs: 1, md: 2 },
  },
  dateText: {
    fontStyle: 'italic',
    color: 'text.secondary',
    display: 'block',
    textAlign: { xs: 'center', md: 'right' },
  },
  title: {
    fontWeight: 700,
    letterSpacing: '-0.5px',
    mt: 1,
  },
  mainGridBox: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    width: '100%',
    gap: 2,
    alignItems: 'flex-start',
  },
  cardContent: {
    flex: 1,
    pr: { md: 4 },
    textAlign: 'left',
  },
  contentBox: {
    color: 'text.secondary',
    lineHeight: 1.6,
    '& p': { margin: 0, padding: 0 },
    '& br': { display: 'inline', lineHeight: '1', margin: 0, padding: 0 },
    '& h1,& h2,& h3,& h4,& h5,& h6': { margin: 0, padding: 0 },
  },
  button: {
    textTransform: 'none',
    fontWeight: 700,
    bgcolor: '#6C7A89',
    color: '#fff',
    px: 3,
    py: 1.1,
    borderRadius: 2,
    boxShadow: 'none',
    '&:hover': { bgcolor: '#556270', boxShadow: 'none' },
  },
  imageBox: {
    width: { xs: '100%', md: '50%' },
    display: 'flex',
    alignItems: 'flex-start',
    position: 'relative',
    alignSelf: 'flex-start',
  },
  image: {
    width: '100%',
    height: { xs: 220, md: 320 },
    borderRadius: 2,
    objectFit: 'cover',
    boxShadow: 3,
    display: 'block',
  },
  authorBadge: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    bgcolor: 'rgba(0,0,0,0.55)',
    color: '#fff',
    px: 1.2,
    py: 0.4,
    borderRadius: 1,
    fontStyle: 'italic',
    fontSize: '0.8rem',
  },
};

export default styles;
