const styles = {
  card: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    p: { xs: 2.5, md: 3.5 },
    borderRadius: 3,
    alignItems: "flex-start",
    border: "1px solid rgba(17, 46, 31, 0.08)",
    boxShadow: "0 12px 34px rgba(18, 39, 30, 0.08)",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    "&:hover": {
      transform: "translateY(-3px)",
      boxShadow: "0 16px 38px rgba(18, 39, 30, 0.12)",
    },
  },
  titleBox: {
    width: "100%",
    textAlign: "center",
    mb: { xs: 1, md: 2 },
  },
  dateText: {
    fontStyle: "italic",
    color: "text.secondary",
    display: "block",
    textAlign: { xs: "center", md: "right" },
  },
  title: {
    fontWeight: 700,
    letterSpacing: "-0.55px",
    mt: 1,
    fontSize: { xs: "1.55rem", md: "2.05rem" },
    lineHeight: 1.15,
    fontFamily: '"Merriweather", "Georgia", serif',
  },
  mainGridBox: {
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    width: "100%",
    gap: 2,
    alignItems: "flex-start",
  },
  cardContent: {
    flex: 1,
    pr: { md: 4 },
    textAlign: "left",
  },
  contentBox: {
    color: "text.secondary",
    fontFamily: '"Inter", "Segoe UI", sans-serif',
    lineHeight: 1.6,
    "& p": { margin: 0, padding: 0 },
    "& br": { display: "inline", lineHeight: "1", margin: 0, padding: 0 },
    "& h1,& h2,& h3,& h4,& h5,& h6": { margin: 0, padding: 0 },
  },
  button: {
    textTransform: "none",
    fontWeight: 700,
    bgcolor: "#4f6f5d",
    color: "#fff",
    px: 3.4,
    py: 1.1,
    borderRadius: 99,
    boxShadow: "0 8px 16px rgba(50, 84, 64, 0.22)",
    "&:hover": {
      bgcolor: "#3f5c4d",
      boxShadow: "0 10px 18px rgba(50, 84, 64, 0.28)",
    },
  },
  imageBox: {
    width: { xs: "100%", md: "50%" },
    display: "flex",
    alignItems: "flex-start",
    position: "relative",
    alignSelf: "flex-start",
  },
  image: {
    width: "100%",
    height: { xs: 220, md: 320 },
    borderRadius: 2.5,
    objectFit: "cover",
    boxShadow: "0 12px 28px rgba(0,0,0,0.12)",
    display: "block",
    border: "1px solid rgba(0,0,0,0.08)",
  },
  authorBadge: {
    position: "absolute",
    bottom: 12,
    right: 12,
    bgcolor: "rgba(10, 24, 17, 0.72)",
    color: "#fff",
    px: 1.2,
    py: 0.5,
    borderRadius: 1,
    fontStyle: "italic",
    fontSize: "0.8rem",
    backdropFilter: "blur(2px)",
  },
};

export default styles;
