const styles = {
  gridItem: {
    pb: 3,
  },
  cardStack: {
    flexDirection: "column",
    gap: 2.5,
    border: "1px solid rgba(0,0,0,0.08)",
    borderRadius: 3,
    p: { xs: 2, md: 3 },
    backgroundColor: "#fff",
    boxShadow: "0 8px 24px rgba(13,38,59,0.06)",
  },
  mainRow: {
    flexDirection: { xs: "column-reverse", md: "row" },
    gap: 2.5,
    width: "100%",
  },
  contentContainer: {
    flexGrow: 1,
  },
  title: {
    fontFamily: '"Merriweather", "Georgia", serif',
    fontSize: { xs: "1.55rem", md: "1.9rem" },
    fontWeight: 700,
    letterSpacing: "-0.4px",
    lineHeight: 1.2,
    mb: 1,
  },
  date: {
    fontStyle: "italic",
    color: "text.secondary",
    display: "block",
    mb: 1.5,
  },
  postPreview: {
    color: "text.secondary",
    fontFamily: '"Inter", "Segoe UI", sans-serif',
    lineHeight: 1.6,
    "& p": { margin: 0, padding: 0 },
    "& br": { display: "inline", lineHeight: "1", margin: 0, padding: 0 },
    "& h1,& h2,& h3,& h4,& h5,& h6": { margin: 0, padding: 0 },
  },
  actionRow: {
    mt: 0.25,
    flexWrap: "wrap",
    width: "100%",
    gap: 1.5,
    justifyContent: { xs: "flex-start", md: "space-between" },
    rowGap: 1.1,
  },
  adminActionGroup: {
    gap: 1,
    flexWrap: "wrap",
    ml: { xs: 0, md: "auto" },
    justifyContent: "flex-end",
    width: "fit-content",
  },
  readMoreButton: {
    textTransform: "none",
    fontWeight: 700,
    bgcolor: "#6C7A89",
    color: "#fff",
    px: 2.6,
    py: 1,
    borderRadius: 2,
    boxShadow: "none",
    "&:hover": { bgcolor: "#556270", boxShadow: "none" },
  },
  adminActionIcon: {
    fontSize: "1.06rem",
  },
  actionButton: {
    textTransform: "none",
    fontWeight: 700,
    borderRadius: 99,
    px: 1.5,
    py: 0.52,
    borderColor: "rgba(37, 70, 55, 0.35)",
    color: "#2f5644",
    bgcolor: "rgba(255,255,255,0.9)",
    "&:hover": {
      borderColor: "#2f5644",
      bgcolor: "#eef4f0",
    },
  },
  deleteButton: {
    textTransform: "none",
    fontWeight: 700,
    borderRadius: 99,
    px: 1.5,
    py: 0.52,
    borderColor: "rgba(198, 40, 40, 0.35)",
    color: "#c62828",
    bgcolor: "rgba(255,255,255,0.95)",
    "&:hover": {
      borderColor: "#b71c1c",
      bgcolor: "#fff1f1",
    },
  },
  imageColumn: {
    width: { xs: "100%", md: 260 },
    flexShrink: 0,
  },
  imageFrame: {
    width: "100%",
    height: { xs: 230, md: 300 },
    border: "1px solid rgba(0,0,0,0.09)",
    borderRadius: 2.5,
    overflow: "hidden",
    position: "relative",
    boxShadow: "0 10px 24px rgba(0,0,0,0.08)",
  },
  image: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  authorBadge: {
    position: "absolute",
    bottom: 12,
    right: 12,
    bgcolor: "rgba(0,0,0,0.58)",
    color: "#fff",
    px: 1.2,
    py: 0.45,
    borderRadius: 1,
    fontStyle: "italic",
    fontSize: "0.78rem",
    maxWidth: "68%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  featureButton: {
    position: "absolute",
    top: 10,
    left: 8,
    textTransform: "none",
    fontWeight: 700,
    fontSize: "0.78rem",
    borderRadius: 99,
    px: 1.15,
    py: 0.22,
    minHeight: 30,
    color: "#fff",
    backgroundColor: "rgba(42, 82, 62, 0.9)",
    boxShadow: "0 6px 14px rgba(12, 34, 24, 0.24)",
    "&:hover": {
      backgroundColor: "rgba(37, 70, 55, 0.95)",
      boxShadow: "0 8px 14px rgba(12, 34, 24, 0.28)",
    },
  },
  featureButtonIcon: {
    fontSize: "1rem",
    color: "#ffb300",
  },
  featuredBadge: {
    position: "absolute",
    top: 10,
    left: 8,
    display: "inline-flex",
    alignItems: "center",
    gap: 0.55,
    px: 1.2,
    py: 0.42,
    borderRadius: 99,
    backgroundColor: "rgba(17, 36, 27, 0.82)",
    border: "1px solid rgba(255, 255, 255, 0.22)",
    color: "#fff",
    fontSize: "0.78rem",
    fontWeight: 700,
    letterSpacing: "0.15px",
    backdropFilter: "blur(2px)",
    boxShadow: "0 4px 10px rgba(0,0,0,0.2)",
  },
  featuredBadgeIcon: {
    fontSize: "1rem",
    color: "#ffb300",
  },
};

export default styles;
