const styles = {
  wrapper: {
    position: "relative",
    color: "#fff",
    mb: 3,
    borderRadius: 3,
    overflow: "hidden",
    minHeight: { xs: 240, md: 300 },
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    boxShadow: "0 18px 36px rgba(9, 18, 13, 0.24)",
  },
  overlay: {
    position: "absolute",
    inset: 0,
    background:
      "linear-gradient(120deg, rgba(10, 24, 17, 0.84) 0%, rgba(10, 24, 17, 0.46) 50%, rgba(10, 24, 17, 0.24) 100%)",
  },
  content: {
    position: "relative",
    zIndex: 1,
    p: { xs: 3, md: 4.5 },
    minHeight: { xs: 240, md: 300 },
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    gap: 1.5,
  },
  title: {
    fontFamily: '"Merriweather", "Georgia", serif',
    fontSize: { xs: "1.75rem", md: "2.5rem" },
    lineHeight: 1.14,
    fontWeight: 700,
    letterSpacing: "-0.5px",
    textShadow: "0 3px 14px rgba(0,0,0,0.38)",
    maxWidth: { md: "84%" },
  },
  metaRow: {
    display: "flex",
    alignItems: "center",
    gap: 1.2,
    flexWrap: "wrap",
  },
  metaBadge: {
    bgcolor: "rgba(255,255,255,0.16)",
    border: "1px solid rgba(255,255,255,0.26)",
    px: 1.25,
    py: 0.45,
    borderRadius: 99,
    fontSize: "0.77rem",
    letterSpacing: "0.2px",
    backdropFilter: "blur(2px)",
  },
  authorBadge: {
    position: "absolute",
    right: 14,
    top: 14,
    zIndex: 2,
    bgcolor: "rgba(10, 24, 17, 0.72)",
    color: "#fff",
    border: "1px solid rgba(255,255,255,0.24)",
    px: 1.35,
    py: 0.5,
    borderRadius: 99,
    fontSize: "0.8rem",
    fontStyle: "italic",
    backdropFilter: "blur(2px)",
    maxWidth: "64%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
};

export default styles;
